---
linters-settings:
  # prevent import of "errors" instead of "github.com/pkg/errors"
  depguard:
    rules:
      # Name of a rule.
      main:
        # Packages that are not allowed where the value is a suggestion.
        deny:
          - pkg: "errors"
            desc: Should be replaced by github.com/pkg/errors package

# The most valuable linters; they are required to pass for PR to be merged.
linters:
  disable-all: true
  enable:
    - depguard
    - goimports
    - ineffassign
    - govet
    - staticcheck

issues:
  exclude-use-default: false
