# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ticket.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cticket.proto\x12\x06ticket\"1\n\x0c\x45ventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"3\n\rTicketRequest\x12\x11\n\tticket_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"!\n\x0eTicketResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xc4\x01\n\x06Ticket\x12\x11\n\tticket_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x03 \x01(\t\x12\x16\n\x0e\x64\x61te_purchased\x18\x04 \x01(\x03\x12)\n\x06status\x18\x05 \x01(\x0e\x32\x19.ticket.Ticket.StatusCode\"A\n\nStatusCode\x12\x0b\n\x07PENDING\x10\x00\x12\n\n\x06\x42OOKED\x10\x01\x12\r\n\tCANCELLED\x10\x02\x12\x0b\n\x07INVALID\x10\x03\x32\xf4\x01\n\rTicketService\x12\x34\n\nBookTicket\x12\x14.ticket.EventRequest\x1a\x0e.ticket.Ticket\"\x00\x12?\n\x0c\x43\x61ncelTicket\x12\x15.ticket.TicketRequest\x1a\x16.ticket.TicketResponse\"\x00\x12\x34\n\tGetTicket\x12\x15.ticket.TicketRequest\x1a\x0e.ticket.Ticket\"\x00\x12\x36\n\nGetTickets\x12\x14.ticket.EventRequest\x1a\x0e.ticket.Ticket\"\x00\x30\x01\x42#\n\x12org.example.ticketB\x0b\x45ventTicketP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ticket_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022org.example.ticketB\013EventTicketP\001'
  _globals['_EVENTREQUEST']._serialized_start=24
  _globals['_EVENTREQUEST']._serialized_end=73
  _globals['_TICKETREQUEST']._serialized_start=75
  _globals['_TICKETREQUEST']._serialized_end=126
  _globals['_TICKETRESPONSE']._serialized_start=128
  _globals['_TICKETRESPONSE']._serialized_end=161
  _globals['_TICKET']._serialized_start=164
  _globals['_TICKET']._serialized_end=360
  _globals['_TICKET_STATUSCODE']._serialized_start=295
  _globals['_TICKET_STATUSCODE']._serialized_end=360
  _globals['_TICKETSERVICE']._serialized_start=363
  _globals['_TICKETSERVICE']._serialized_end=607
# @@protoc_insertion_point(module_scope)
