# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x05\x65vent\"\x84\x01\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\x03\x12\x10\n\x08location\x18\x05 \x01(\t\x12\r\n\x05total\x18\x06 \x01(\x05\x12\x0e\n\x06\x62ooked\x18\x07 \x01(\x05\x12\r\n\x05image\x18\x08 \x03(\x0c\"#\n\x08Response\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"\x15\n\x07\x45ventId\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xf0\x01\n\x0c\x45ventService\x12,\n\x0b\x43reateEvent\x12\x0c.event.Event\x1a\x0f.event.Response\x12(\n\x08GetEvent\x12\x0e.event.EventId\x1a\x0c.event.Event\x12,\n\x0bUpdateEvent\x12\x0c.event.Event\x1a\x0f.event.Response\x12.\n\x0b\x44\x65leteEvent\x12\x0e.event.EventId\x1a\x0f.event.Response\x12*\n\nListEvents\x12\x0c.event.Empty\x1a\x0c.event.Event0\x01\x42)\n\x11org.example.eventB\x12\x45ventServiceHelperP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021org.example.eventB\022EventServiceHelperP\001'
  _globals['_EVENT']._serialized_start=23
  _globals['_EVENT']._serialized_end=155
  _globals['_RESPONSE']._serialized_start=157
  _globals['_RESPONSE']._serialized_end=192
  _globals['_EVENTID']._serialized_start=194
  _globals['_EVENTID']._serialized_end=215
  _globals['_EMPTY']._serialized_start=217
  _globals['_EMPTY']._serialized_end=224
  _globals['_EVENTSERVICE']._serialized_start=227
  _globals['_EVENTSERVICE']._serialized_end=467
# @@protoc_insertion_point(module_scope)
