apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: analytics-service-db
  name: analytics-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: analytics-service-db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: analytics-service-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: analytics_db
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: root
          image: postgres:9.6
          name: analytics-service-db
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
