apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: event-service
  name: event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: event-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: event-service
    spec:
      containers:
        - image: mapproject-event-service
          imagePullPolicy: IfNotPresent
          name: event-service
          ports:
            - containerPort: 50051
              protocol: TCP
      restartPolicy: Always
