apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka-ui
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-ui
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kafka-ui
    spec:
      containers:
        - env:
            - name: KAFKA_BROKERCONNECT
              value: "crs-kafka-0.kafka-cluster.default.svc.cluster.local:9092,crs-kafka-1.kafka-cluster.default.svc.cluster.local:9092,crs-kafka-2.kafka-cluster.default.svc.cluster.local:9092"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "crs-kafka-0.kafka-cluster.default.svc.cluster.local:9092,crs-kafka-1.kafka-cluster.default.svc.cluster.local:9092,crs-kafka-2.kafka-cluster.default.svc.cluster.local:9092"
            - name: KAFKA_CLUSTERS_0_NAME
              value: "Kafka Cluster"
          image: provectuslabs/kafka-ui
          name: kafka-ui
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "500Mi"
              cpu: "250m"
      hostname: kafka-ui
      restartPolicy: Always
