apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kong
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kong
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kong
    spec:
      containers:
        - env:
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001, 0.0.0.0:8444 ssl
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_LOG_LEVEL
              value: debug
            - name: KONG_PG_HOST
              value: kong-database
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
          image: kong:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - kong
                - health
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 10
          name: kong
          ports:
            - containerPort: 8000
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
            - containerPort: 8444
              protocol: TCP
          volumeMounts:
            - mountPath: /kong
              name: kong-cm0
            - mountPath: /usr/local/share/lua/5.1/kong/plugins/kong-jwt2header/handler.lua
              name: kong-cm2
              subPath: handler.lua
            - mountPath: /usr/local/share/lua/5.1/kong/plugins/kong-jwt2header/schema.lua
              name: kong-cm3
              subPath: schema.lua
            - mountPath: /etc/kong/kong.conf
              name: kong-cm4
              subPath: kong.conf
            - mountPath: /usr/include/google
              name: gprotos
      restartPolicy: Always
      volumes:
        - configMap:
            name: kong-cm0
          name: kong-cm0
        - configMap:
            items:
              - key: handler.lua
                path: handler.lua
            name: kong-cm2
          name: kong-cm2
        - configMap:
            items:
              - key: schema.lua
                path: schema.lua
            name: kong-cm3
          name: kong-cm3
        - configMap:
            items:
              - key: kong.conf
                path: kong.conf
            name: kong-cm4
          name: kong-cm4
        - name: gprotos
          hostPath:
            path: /google