apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kong-database
  name: kong-database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kong-database
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kong-database
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: kong
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_USER
              value: kong
          image: postgres:9.6
          imagePullPolicy: IfNotPresent
          name: kong-database
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: kong-db-pvc
      restartPolicy: Always
      volumes:
        - name: kong-db-pvc
          persistentVolumeClaim:
            claimName: kong-db-pvc
