apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ticket-service
  name: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ticket-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ticket-service
    spec:
      containers:
        - env:
            - name: DB_PASSWORD
              value: admin
            - name: DB_USER
              value: root
            - name: MYSQL_HOST
              value: ticket-service-db
            - name: MYSQL_PORT
              value: "3306"
          image: mapproject-ticket-service
          name: ticket-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              protocol: TCP
      restartPolicy: Always
