apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ticket-service-db
  name: ticket-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ticket-service-db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ticket-service-db
    spec:
      containers:
        - image: mapproject-ticket-service-db
          name: ticket-service-db
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"
      restartPolicy: Always
