apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user-service-db
  name: user-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service-db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: user-service-db
    spec:
      containers:
        - image: mongo:latest
          imagePullPolicy: IfNotPresent
          name: user-service-db
          ports:
            - containerPort: 27017
              protocol: TCP
      restartPolicy: Always
