version: '3'

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    networks:
      - kong-net
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_HOST_AUTH_METHOD: trust

  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    networks:
      - kong-net
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database

  kong:
    image: kong:latest
    container_name: kong
    networks:
      - kong-net
    ports:
      - "9000:8000"
      - "9443:8443"
      - "9001:8001"
      - "9444:8444"
    environment:
      KONG_LOG_LEVEL: debug
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    depends_on:
      - kong-migrations
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:20

  kong-configure:
    build: .
    container_name: kong-configure
    # command: sh -c "pwd && sleep 10 && configure-kong.sh"
    networks:
      - kong-net
    depends_on:
      - kong
    restart: on-failure:20

networks:
  kong-net:
    name: kong-net
    external: true